### ISSUE TITLE
Change arguments to Index # and RGB Value

### ISSUE THREAD

**Issue by ghost** [rlipscombe/ConsoleColors#1]
Hey there!

This is fantastic! I have not found any other solution like this for PowerShell so this is a total godsend! Admittedly, I know next to nothing about C# so one thing I was wondering is, could this be modified to use as the arguments, index values 0-15 and rgb values respectively, instead of color-name strings?

I ask especially about the rgb option because I wonder if custom colors could be used instead (like a solarized theme or something).

Either way, thanks for this project! Totally came in handy for me!

-M

**Comment by rlipscombe** [comment]
That's already supported:

```
$index = [ConsoleColor]5
$a = 255,
$r = 11,
$g = 22,
$b = 33,
$color = [System.Drawing.Color]::FromArgb($a, $r, $g, $b)
[ConsoleColors.ConsoleEx]::SetColor($index, $color)
```

I've updated the README.
